.syntax unified
.cpu cortex-m0plus
.thumb

/*
 * uint16_loop_test.s — Exercises ldrh / strh / uxth, generated by GCC for
 * code that uses uint16_t loop variables.  Equivalent to:
 *
 *   #include <stdint.h>
 *   int main(void) {
 *       uint16_t i;
 *       for (i = 0; i <= 49; i++) {}
 *       return 0;
 *   }
 *
 * Returns 0 on success, 1 if the loop ran the wrong number of iterations.
 *
 * This also exercises the PC-relative LDR (.L5) which appears at a 2-mod-4
 * address in the GCC output — the instruction that originally exposed the
 * PC-offset bug.
 */

asm_main:
        push    {r7, lr}
        sub     sp, sp, #8
        add     r7, sp, #0
        adds    r3, r7, #6      @ r3 = &i  (16-bit slot on the stack)
        movs    r2, #0
        strh    r2, [r3]        @ i = 0
        b       .L2

.L3:
        adds    r3, r7, #6
        ldrh    r3, [r3]        @ r3 = (uint16_t) i
        uxth    r3, r3          @ zero-extend to 32 bits
        adds    r3, r3, #1      @ r3 = i + 1
        uxth    r2, r3          @ r2 = (uint16_t)(i+1)
        adds    r3, r7, #6
        strh    r2, [r3]        @ i++

.L2:
        adds    r3, r7, #6
        ldrh    r3, [r3]        @ r3 = (uint16_t) i
        uxth    r3, r3
        ldr     r2, .L5         @ r2 = 49  (PC-relative load, lands at 2 mod 4)
        cmp     r3, r2
        bls     .L3             @ loop while i <= 49

        @ verify i == 50
        adds    r3, r7, #6
        ldrh    r3, [r3]
        uxth    r3, r3
        movs    r2, #50
        cmp     r3, r2
        beq     .Lpass
        movs    r3, #1          @ failure: return 1
        b       .Ldone
.Lpass:
        movs    r3, #0          @ success: return 0
.Ldone:
        movs    r0, r3
        mov     sp, r7
        add     sp, sp, #8
        pop     {r7, pc}

        .align 2
.L5:
        .word   49
